### ISSUE TITLE
could stale and merged branches be removed?

### ISSUE THREAD

**Issue by Idrinth** [giorgiosironi/eris#119]
The repository currently has 1 active and 55 inactive branches.
This makes it unnecessarily hard to figure out if there are still unfinished features hidden somewhere, that could/should be completed, because those branches get lost among all the other branches avaible.

Is there any reason to keep branches that have already been merged?

**Comment by giorgiosironi** [comment]
Not much, just that Github does not provide a easy way to automate deletion (e.g. every time a PR is merged). https://github.com/giorgiosironi/eris/branches distinguishes between merged branches (not useful anymore) and the rest. I'll do a round of pruning now.

In general, is there is something unfinished it's in an open pull request.

**Comment by giorgiosironi** [comment]
https://github.com/giorgiosironi/eris/branches/all looks much leaner now.
