### ISSUE TITLE
Upgrade forAll and suchThat to new PHPUnit constraint class

### ISSUE THREAD

**Issue by Vinai** [giorgiosironi/eris#121]
Since PHPUnit 6 the abstract class `\PHPUnit_Framework_Constraint` has been deprecated by the class `\PHPUnit\Framework\Constraint\Constraint`.  
PHPUnit 6 was released on the 3. February 2017.

The `ForAll::when` quantifier method and the `SuchThatGenerator` allow passing a PHPUnit constraints as a type predicate.
The code in question still checks for the old pre-PHPUnit 6 class name.
Would you be open to a PR to update this to the new class name?

Even though this would be a backward incompatible change, I think it would be the right move to keep it compatible with new versions of PHPUnit.

Affected classes:
https://github.com/giorgiosironi/eris/blob/master/src/Quantifier/ForAll.php#L99
https://github.com/giorgiosironi/eris/blob/master/src/Generator/SuchThatGenerator.php#L91

**Comment by giorgiosironi** [comment]
Yes, it is reasonable to update as PHPUnit 6 is already an unsupported version. Backward incompatibility sometimes happens as there are only 0.x versions of Eris released.

**Comment by Vinai** [comment]
This already has been implemented.
