### ISSUE TITLE
Expose protected \Eris\TestTrait::limitTo via \Eris\Facade

### ISSUE THREAD

**Issue by Vinai** [giorgiosironi/eris#122]
The method `\Eris\TestTrait::limitTo` is currently protected, so it is not possible to call it when using `\Eris\Facade`.

Would you be open to a PR to make `limitTo` public?
This would be a backward compatible change.

Alternatively a new public method `Facade::limit` could be added that passes the call through to the trait. As far as I can see that would also be a backward compatible change.

NOTE: The same applies to `minimumEvaluationRatio`, `shrinkingTimeLimit` and `withRand`.
Would you prefer to handle these at the same time or in separate issues?

**Comment by Vinai** [comment]
Just noticed the PR https://github.com/giorgiosironi/eris/pull/110

**Comment by giorgiosironi** [comment]
The PR (or a separate one) needs to be updated for the current `master` and to get a green build. I am favorable to this change, no compatibility problems and better reuse through `Facade`.
