### ISSUE TITLE
BooleanGenerator::shrink() returns a different type to Generator::shrink()

### ISSUE THREAD

**Issue by brewers-dev-alex** [giorgiosironi/eris#123]
The Generator interface defines the return type of shrink() as GeneratedValueSingle<T>|GeneratedValueOptions<T>, but BooleanGenerator::shrink() returns false.

This will cause an error if anyone tries to call a method on the return value of shrink(). For example, if a tuple contains just two booleans it will error with "Call to a member function add() on boolean" in optionsFromTheseGenerators() on line 68.

**Comment by ilario-pierbattista** [comment]
Fix merged in #131
