### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Vinai** [giorgiosironi/eris#133]
There hasn't been an update in a long time, and pull requests and issues have been going unanswered.
@giorgiosironi do you want to continue to maintain this project?

**Comment by giorgiosironi** [comment]
Hello,
I am maintaining this outside of a full time job so have limited time outside of it to follow open source; just saw your sequence of pull requests, which I'll review now.

**Comment by ilario-pierbattista** [comment]
Hi @Vinai,

last month @giorgiosironi gave write rights to @davedevelopment and me.
I hope to be helpful to the project.
