### ISSUE TITLE
PhpStan complains about Generator functions not found

### ISSUE THREAD

**Issue by aszenz** [giorgiosironi/eris#134]
Thanks for making this library, I added some tests that run successfully in phpunit but our static analyzer phpstan (https://github.com/phpstan/phpstan) seems to not find eris generator functions.

Example:
```
use Eris\Generator as Generator;
use Eris\Quantifier\ForAll;
use Eris\TestTrait as ErisTestTrait;
use PHPUnit\Framework\TestCase;

final class DateFunctionsTest extends TestCase 
{
    use ErisTestTrait;

    private function forAllDateSamples(): ForAll
    {
        $dateRange1 = Generator\date('2020-01-01T00:00:00', '2020-12-31T00:00:00');
        $dateRange2 = Generator\date('2021-01-01T00:00:00', '2021-12-31T00:00:00');

        return $this->forAll(
            $dateRange1,
            Generator\oneOf(
                $dateRange1,
                $dateRange2
            )
        );
    }
```

Output from phpstan:
```
 <error line="90" column="1" severity="error" message="Function Eris\Generator\date not found." />
  <error line="91" column="1" severity="error" message="Function Eris\Generator\date not found." />
  <error line="95" column="1" severity="error" message="Function Eris\Generator\oneOf not found." />
```

Looking at how these functions are defined, I'm not sure how composer is able to autoload them i.e function and class in a single file.

Is there anything I can add via annotations that would allow phpstan to find these functions, the bigger issue is if this library is compatible with static type checkers like phpstan.

Thanks

**Comment by ilario-pierbattista** [comment]
#145 partially solves the issue. Generator constructors as functions outside classes will be deprecated soon.
Just substitute `Eris\Generator\<generator_name>(...)` with `Eris\Generators::<generator_name>`.
