### ISSUE TITLE
Failing tests on latest PHPUnit due to removal of internal method

### ISSUE THREAD

**Issue by aszenz** [giorgiosironi/eris#142]
The internal method of PHPUnit `getAnnotations` used in TestTrait here https://github.com/giorgiosironi/eris/blob/1210237f70653fe5a100f3ff99be8f19905e6eec/src/TestTrait.php#L54 has been removed from PHPUnit in this commit https://github.com/sebastianbergmann/phpunit/commit/68582043e149039cfa3596b42ed35753dcf54fb2

The alternative is to use:
```php
        $tags = \PHPUnit\Util\Test::parseTestMethodAnnotations(
            get_class($this),
            $this->getName(false)
        );
```
Let me know if this change is ok, i'll create a pr then, as far as i know this change should also work with older phpunit versions.

**Comment by ilario-pierbattista** [comment]
Hi @aszenz, sure, a PR will be welcome.
Please pay attention to the `\Eris\Facade::getAnnotations`.
At a first sight, I would encapsulate your snippet in another function to be overridden in the Facade.

**Comment by aszenz** [comment]
> Hi @aszenz, sure, a PR will be welcome.
> Please pay attention to the `\Eris\Facade::getAnnotations`.
> At a first sight, I would encapsulate your snippet in another function to be overridden in the Facade.

I changed the method used in facade to point to a new method `getTestCaseAnnotations`
