### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by seb-celinedesign** [giorgiosironi/eris#149]
Following errors occurs with php 8.1 : 
`Deprecated: Return type of Eris\Generator\GeneratedValueOptions::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/seb/Sites/pepinieres-frances.com/vendor/giorgiosironi/eris/src/Generator/GeneratedValueOptions.php on line 119
PHP Deprecated:  Return type of Eris\Generator\GeneratedValueOptions::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/seb/Sites/pepinieres-frances.com/vendor/giorgiosironi/eris/src/Generator/GeneratedValueOptions.php on line 124`

**Comment by ilario-pierbattista** [comment]
Hi @seb-celinedesign I'm trying to extend support to PHP 8.1 in #148

**Comment by ilario-pierbattista** [comment]
Released in https://github.com/giorgiosironi/eris/releases/tag/0.13.0
