### ISSUE TITLE
Provide compatibility with PHPUnit 10

### ISSUE THREAD

**Issue by Pixelshaped** [giorgiosironi/eris#163]
Currently the code relies on at least a method that has been deleted from PHPUnit 10
```
\PHPUnit\Util\Test::parseTestMethodAnnotations
```
In `TestTrait::getTestCaseAnnotations`

**Comment by Pixelshaped** [comment]
@giorgiosironi Hello! What do you think would be the best course of action? A new major version with dropped support for Annotations and added support for Attributes, or on the contrary a more bc-compatible implementation relying on doctrine/annotation-reader, and optional support for Attributes?

**Comment by ilario-pierbattista** [comment]
Hi @Pixelshaped, I think the second one would be better. However, even if relying on doctrine/annotation-reader, it would be better to mark as deprecated the use of annotations.

**Comment by ilario-pierbattista** [comment]
Resolved by #164 , released as 1.0.0-rc1 https://github.com/giorgiosironi/eris/releases/tag/1.0.0-rc1
