### ISSUE TITLE
PHPUnit 11 support

### ISSUE THREAD

**Issue by Pixelshaped** [giorgiosironi/eris#174]
Hi there!

Following my previous work (#164) I'm probably going to submit a new PR to solve some of PHPUnit 11 deprecations. From what I've seen, this is mainly linked to `@before` `@beforeClass` and other annotations that have become unsupported (and that I could have removed last time, alas I had no warning about them).

Is a PR welcome @giorgiosironi ? That could be RC2.

Thanks :)

**Comment by ilario-pierbattista** [comment]
Hi @Pixelshaped 

> Is a PR welcome @giorgiosironi ? That could be RC2.

Sure! I just did a quick merge master -> 1.x.x. Psalm is failing for some reason, but every other check went well.

You're effort is really appreciated
