### ISSUE TITLE
Generation of 2D arrays with consistent row lengths

### ISSUE THREAD

**Issue by sivlev** [giorgiosironi/eris#180]
I have a project where I work with 2D arrays (a kind of matrix arithmetics for linear algebra). Is there a way how I can generate numeric arrays of n x m size? I tried the following way:
```
Generator\seq(
    Generator\seq(
        Generator\oneOf(
            Generator\int(),
            Generator\float(),
        )
    )
);
```
But the problem here is that the row lengths in such an array are inconsistent with each other: The first row may contain, let's say, 10 elements, the second row may contain 5 elements, etc. Whereas a matrix array must be of rectangular shape, i.e. all rows must have same number of columns. As a workaround, I use a check in `when()` if the generated array is rectangular but this is not optimal since very few randomly generated arrays are rectangular. Is there maybe a better way to achieve that?

**Comment by sivlev** [comment]
Thank you! I thought yesterday actually about using vectors but, as far as I understand, I can then only generate matrices of one fixed size (e.g. 5x3 as in your sample code), or? Is it not possible at the moment to generate matrices (or multidimensional arrays in general) of random sizes?

**Comment by ilario-pierbattista** [comment]
Sure, you can combine generators with `bind`. It take a generator and creates another generator using the values from the first one.

```php
     $this->forAll(
            Generators::bind(
                Generators::associative(
                    [
                        'rows' => Generators::choose(2, 10),
                        'columns' => Generators::choose(2, 10),
                    ]
                ),
                function ($spec) {
                    ['rows' => $rows, 'columns' => $columns] = $spec;

                    return Generators::vector(
                        $rows,
                        Generators::vector(
                            $columns,
                            Generators::oneOf(Generators::float(), Generators::int())
                        )
                    );
                }
            )
        )->then(function ($in) {

            $firstRowSize = count($in[0]);
            foreach ($in as $item) {
                self::assertCount($firstRowSize, $item);
            }
        });
```

**Comment by sivlev** [comment]
I overlooked somehow the `bind` method. This way it should definitely work. Many thanks!

**Comment by ilario-pierbattista** [comment]
In case you'd need some extra examples, I was preparing [this snippet](https://gist.github.com/ilario-pierbattista/3fdd4589752a11c6ce00a80d535c3668).

You're welcome :)
