### ISSUE TITLE
Choice of shrinking function for integers requires O(n) shrinks

### ISSUE THREAD

**Issue by DRMacIver** [giorgiosironi/eris#46]
Hey,

So I'm not a user of your library, I'm the author of [Hypothesis](http://hypothesis.readthedocs.org/), a Quickcheck for Python.

I happened across this while I was collating a list of implementations for different languages. It looks like a good job!

But on looking through the code, I see you've made the same mistakes I made with shrinking functions back at the beginning. Basically shrinking works much better if you try to start from simpler versions and move up to complex ones rather than making small changes to the original. I noticed this in the context of your integer shrinks which only adjust by a distance of one each time. This means that when you're shrinking an integer it will take you O(n) shrinks to get to the smallest value, but you should usually be able to do it in O(log(n)) by having it basically do a binary search down to the value.

The context I noticed this in was actually in putting together a talk about example shrinking. You might find the [slides interesting](http://drmaciver.github.io/hypothesis-talks/hypothesis-simplification-bigo.html#/intro) (there may also be a video at some point, which I'll transcribe). I also [wrote a little](http://www.drmaciver.com/2015/03/simplify-starts-from-the-wrong-end/) about this when I first figured it out. 

Obviously you should feel free to ignore this advice if this isn't a problem for you in practice, but if you find you have weird and annoying performance problems with shrinking this is probably what's going on. :-)

**Comment by giorgiosironi** [comment]
This is an interesting direction to go into, thanks :) I will look into the resources you've linked

**Comment by gabrielelana** [comment]
Thanks @DRMacIver :+1:

**Comment by giorgiosironi** [comment]
https://github.com/giorgiosironi/eris/pull/87 closes this, as there is now the option for Generators to provide a set of options for shrinking to use to bring the search down to O(log n). For example, the integer `100` can specify as options `50`, `75`, `88`, `94`, `97`, and `99`.
