### ISSUE TITLE
Float and String generators won't work in PHP 7

### ISSUE THREAD

**Issue by MontealegreLuis** [giorgiosironi/eris#55]
Hi,

`Float` and `String` won't be valid class names in PHP 7.

http://php.net/manual/en/reserved.other-reserved-words.php

They could be renamed to something like `FloatGenerator` and `StringGenerator`. If you think those are good names I could create a PR for this.

**Comment by giorgiosironi** [comment]
Yes, these are good names.it's a diffused convention to use `"{$qualifier}{$interface}"` and $interface is `Generator` here.

**Comment by giorgiosironi** [comment]
Considering closed by #56
